apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-image-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-image-generator
  template:
    metadata:
      labels:
        app: ai-image-generator-cpu
    spec:
      containers:
      - name: ai-image-generator-cpu
        image: us-docker.pkg.dev/ai-on-gke-image-generator/ai-image-generator/ai-image-generator-cpu:latest
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ai-image-generator-svc
spec:
  type: LoadBalancer
  selector:
    app: ai-image-generator
  ports:
  - port: 80
    targetPort: 8080
